diff --git a/src/Makefile b/src/Makefile
index bc25aba..8b2e140 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -57,11 +57,7 @@ INSTALL = install
 
 DESTDIR ?=
 
-ifeq ($(shell uname -m),x86_64)
-	LIBSUBDIR := lib64
-else
-	LIBSUBDIR := lib
-endif
+LIBSUBDIR := lib
 
 PREFIX ?= /usr
 LIBDIR ?= $(PREFIX)/$(LIBSUBDIR)
