// Code generated by scripts/generate-structures - DO NOT EDIT.
// to modify, regenerate after modifying templates/probe.h.j2

#ifndef __PROBE_H
#define __PROBE_H

#include "probe.bpf.h"
#include <stdint.h>

// this header contains forward declarations
// for the userspace side of things

struct state;

// begin bprm_check_security

typedef void
bprm_check_security_event_handler(void *ctx, unsigned long ts,
                                  struct bpf_bprm_check_security_event_t e);

// end bprm_check_security

struct state_configuration {
  unsigned int filtered_uid;
  unsigned char debug;
  void *bprm_check_security_ctx;
  bprm_check_security_event_handler *bprm_check_security_handler;
};

struct state *new_state(struct state_configuration config);
void destroy_state(struct state *self);
void poll_state(struct state *s, int timeout);

#endif /* __PROBE_H */