[package]
name = "probe-sys"
version = "0.0.1"
authors = ["Andrew Stucki <andrew.stucki@gmail.com>"]
license = "GPL"
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["rlib"]

[build-dependencies]
protobuf-codegen-pure = "2.3"
